### ISSUE TITLE
New tab won't open by doubleclicking tab area / clicking "Open a new tab" button

### ISSUE THREAD

**Issue by allixx** [traxium/tabtree#193]
Tab Tree 1.4.8 / Firefox 51.0 x64 / Win7. Cannot open a new tab by doubleclicking or middle-clicking tab area, or pressing "Open a new tab" button - nothing happens. "Open a new tab..." tab area popup menu items work. Default new tab shortcut Ctrl + T works as well.

All of those actions worked previously in Firefox 50 x64 / Win7.

EDIT: I don't see any documented Firefox 51 changes even remotely relevant to this issue. Does anyone have a suggestion how to approach debugging of this? I tried builtin Firefox addon debuger, but it fails to attach to Tab tree.

**Comment by RokuZero** [comment]
I have same problem. Debian testing x64. firefox 51.

**Comment by igordavid** [comment]
Same issue here - Firefox 51 64-bit, MAC Version 10.11.6

Double-click on the empty area doesn't open a new tab. It was working before in previous version of Firefox.

The same issue is happening with "Tree Style Tab", also I tried add-on "Classic theme restorer" but didn't help.

Anyone found a solution?

Thanks in advance!

**Comment by elrac** [comment]
Also not working in Firefox 51.0.1 (32-bit) in Windows 10. 

None of the methods of opening a new tab other than ctrl-t work. I tested double click, scroll click, and clicking the + button.

**Comment by freeseacher** [comment]
Same on linux mint ff 51

**Comment by mrd000** [comment]
I have the same problem on the most recent version @traxium.
The error in the console is:
`TypeError: aDOMWindow.BrowserOpenNewTabOrWindow is not a function bootstrap.js:2758:4`

**Comment by allixx** [comment]
https://github.com/mozilla/amo-validator/issues/473

Replacing BrowserOpenNewTabOrWindow calls with BrowserOpenTab seem to solve this. But due to impossibility of using non signed addons in branded Firefox, author has to fix this himself, or someone has to fork Tab tree and register as a new component. :(

**Comment by allixx** [comment]
duplicate of https://github.com/traxium/tabtree/issues/170
apparently it is already fixed in master, just not released as a new version. :)

**Comment by mrd000** [comment]
Should we keep this open until a new version is released then? Because it's still a problem and it's not gone away.

**Comment by allixx** [comment]
request to the author to release updated version should be in a different issue, I think.
